/*
* Generated file
*
* Generated from: yang module name: msncc-provider-impl yang module local name: msncc-provider-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Tue Aug 19 17:25:11 PDT 2014
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.lispflowmapping.config.yang.netconf.impl;
public class MsNCCProviderModuleFactory extends org.opendaylight.lispflowmapping.config.yang.netconf.impl.AbstractMsNCCProviderModuleFactory {

}
