/*
* Generated file
*
* Generated from: yang module name: msncc-provider-impl yang module local name: msncc-provider-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Tue Jul 08 10:01:30 CEST 2014
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.lispflowmapping.config.yang.mappingservice.netconf.impl;
public class MsNCCProviderModuleFactory extends org.opendaylight.lispflowmapping.config.yang.mappingservice.netconf.impl.AbstractMsNCCProviderModuleFactory {

}
