/*
* Generated file
*
* Generated from: yang module name: toaster-provider-impl yang module local name: toaster-provider-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Mon Jul 07 19:23:37 CEST 2014
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.lispflowmapping.config.yang.mappingservice.toaster_impl;
public class ToasterProviderModuleFactory extends org.opendaylight.lispflowmapping.config.yang.mappingservice.toaster_impl.AbstractToasterProviderModuleFactory {

}
