/*
* Generated file
*
* Generated from: yang module name: msncc-provider-impl yang module local name: msncc-provider-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Mon Jul 07 20:15:23 CEST 2014
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.lispflowmapping.config.yang.mappingservice.netconf_impl;
public class MsNCCProviderModuleFactory extends org.opendaylight.lispflowmapping.config.yang.mappingservice.netconf_impl.AbstractMsNCCProviderModuleFactory {

}
